// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";



import { TImmutableDBKeys } from "./models";

export const ConsumerSecretsSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  orgId: z.string().uuid(),
  titleCiphertext: z.string(),
  titleIV: z.string(),
  titleTag: z.string(),
  typeCiphertext: z.string(),
  typeIV: z.string(),
  typeTag: z.string(),
  dataCiphertext: z.string(),
  dataIV: z.string(),
  dataTag: z.string(),
  commentCiphertext: z.string(),
  commentIV: z.string(),
  commentTag: z.string(),
  algorithm: z.string().default('aes-256-gcm'),
  keyEncoding: z.string().default('utf8'),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TConsumerSecrets = z.infer<typeof ConsumerSecretsSchema>;
export type TConsumerSecretsInsert = Omit<z.input<typeof ConsumerSecretsSchema>, TImmutableDBKeys>;
export type TConsumerSecretsUpdate = Partial<Omit<z.input<typeof ConsumerSecretsSchema>, TImmutableDBKeys>>;
